version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aos_db
      POSTGRES_USER: aos_user
      POSTGRES_PASSWORD: aos_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./shared/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - aos_network

  # Core Services
  orchestration_agent:
    build: ./services/core_services/orchestration_agent
    environment:
      - DATABASE_URL=postgresql://aos_user:aos_password@postgres:5432/aos_db
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - aos_network
    volumes:
      - ./services/core_services/orchestration_agent:/app

  # Frontend UI
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - aos_network
    volumes:
      - ./ui:/app
      - /app/node_modules

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./deployment/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - aos_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - aos_network

networks:
  aos_network:
    driver: bridge

volumes:
  postgres_data:
  sandbox_storage:
  production_storage:
  grafana_data:
