route:
  group_by: ['alertname', 'service', 'environment']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack'
  routes:
  - match:
      severity: 'critical'
    receiver: 'slack-critical'
    repeat_interval: 30m

receivers:
- name: 'slack'
  slack_configs:
  - api_url: ${SLACK_WEBHOOK_URL:-''}
    channel: '#monitoring'
    send_resolved: true
    title: '{{ template "slack.default.title" . }}'
    text: '{{ template "slack.default.text" . }}'
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

- name: 'slack-critical'
  slack_configs:
  - api_url: ${SLACK_WEBHOOK_URL:-''}
    channel: '#alerts-critical'
    send_resolved: true
    title: '🚨 CRITICAL: {{ template "slack.default.title" . }}'
    text: '{{ template "slack.default.text" . }}'
    color: 'danger'

templates:
- '/etc/alertmanager/templates/*.tmpl'
