global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orchestration-agent'
    static_configs:
      - targets: ['orchestration_agent:8000']
  
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
